WebJsonToDB/Models/ErrorViewModel.cs
using System;

namespace WebJsonToDB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebJsonToDB/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebJsonToDB.Controllers
{
    public class CreateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add([FromBody] JObject data)
        {
            GenerateDB gen = new GenerateDB();
            string json = data.ToString();
            Dictionary<string, string> fields = JsonConvert.DeserializeObject<Dictionary<string, string>>(json);

            string nameTable = "";
            foreach (var i in fields)
            {
                nameTable = i.Value;
                break;
            }
            fields.Remove("nameTable");

            gen.Create(nameTable, fields);
            
            return View();
        }
    }
}

WebJsonToDB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebJsonToDB.Models;

namespace WebJsonToDB.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            dynamic table = Tables.GetTables();
            ViewBag.Tables = table;

            return View();
        }
        
        
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebJsonToDB/Controllers/OpenController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebJsonToDB.Controllers
{
    public class OpenController : Controller
    {
        public static string Id = "";
        public static string Table = "";
        public static string FColumn = "";
        public static string NameTable = "";

        public IActionResult Index(string nameTable)
        {
            dynamic colums = Tables.GetAllRows(nameTable);
            dynamic columNames = Tables.GetColumsName(nameTable);
            NameTable = nameTable;

            int count = columNames.Count;
            List<dynamic> id = new List<dynamic>();
            bool check = false;

            foreach (var i in colums)
            {
                foreach (var k in i)
                {
                    if (!check)
                    {
                        id.Add(k.Value);
                    }
                    check = true;
                }
                check = false;
            }

            ViewBag.Id = id;

            ViewBag.FColumn = columNames[0];
            ViewBag.Count = count;
            ViewBag.Colums = colums;
            ViewBag.ColumNames = columNames;
            ViewBag.Table = nameTable;

            return View();
        }

        public IActionResult Redirect()
        {
            return Redirect("/Open?nameTable=" + NameTable);
        }

        public IActionResult Delete(string id, string table, string fcolumn)
        {
            string sql = Tables.Delete(id, table, fcolumn);
            return Redirect("/Open?nameTable=" + table);
        }

        [HttpGet]
        public IActionResult Edit(string id, string table, string fcolumn)
        {
            dynamic row = Tables.GetRow(id, table, fcolumn);
            List<dynamic> values = new List<dynamic>();

            foreach (var i in row)
            {
                foreach (var k in i)
                {
                    values.Add(k.Value);
                }
                
            }
            Id = id;
            Table = table;
            FColumn = fcolumn;

            ViewBag.Id = id;
            ViewBag.RowInfo = row;
            ViewBag.Values = values;
            ViewBag.Fcolumn = fcolumn;
            return View();
        }

        [HttpPost]
        public IActionResult Edit(params string[] par)
        {
            string sql = Tables.Update(Id, Table, FColumn, par);
            return Redirect("/Open?nameTable=" + Table);
        }

        [HttpGet]
        public IActionResult Create(string table)
        {
            List<string> list = Tables.GetColumsName(table);
            Table = table;
            ViewBag.ColumsName = list;
            return View();
        }

        [HttpPost]
        public IActionResult Create([FromBody] JObject data)
        {
            GenerateDB gen = new GenerateDB();
            string json = data.ToString();
            dynamic values = JsonConvert.DeserializeObject<Dictionary<string, string>>(json);
            gen.AddData(Table, values);
            ViewBag.Table = Table;

            return Redirect("/Open?nameTable=" + Table);
        }
    }
}

WebJsonToDB/Views/Create/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Name table</h2>
<input class="form-control" id="nameTable" style="width:15%"/>
<div class="form-horizontal">
    <hr />
    <div class="row row-centered d-inline-flex">
        <div class="inputs col-sm-2 mt-2">
            <input class="form-control" id="id-1" name="nameInput" />
        </div>
        <div class="selects col-sm-2">
            <select class="form-control" id="id-sel-1" name="nameType">
                <option value="string">string</option>
                <option value="int">int</option>
                <option value="decimal">decimal</option>
            </select>
        </div>
    </div>
    <br/>
    <input class="btn btn-info" type="button" onclick="add_input(), add_select()" value="Добавить строку" />
    <input class="btn btn-info" type="submit" id="sub" value="Создать" />
</div>

<h2 id="h2"></h2>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    var incr = 2;
    function add_input() {
        console.log('input');
        var inputs = $('.inputs input[type="text"]');
        var new_id = incr;
        $('.inputs').append('<input class="form-control" id="id-' + new_id + '" name="name[]" />');
    }
    function add_select() {
        console.log('select');
        var new_id = incr;
        incr++;
        $('.selects').append('<select class="form-control" id="id-sel-' + new_id + '" name="nameType">'
            + '<option value = "string">string</option>'
            + '<option value = "int" >int</option >'
            + '<option value = "decimal" >decimal</option >'
            + '</select > ');
    }


    $('#sub').click(function (e) {
        e.preventDefault();

        var dict = {};

        dict['nameTable'] = $('#nameTable').val();
        for (var i = 1; i < incr; i++) {
            dict[$('#id-' + i + '').val()] = $('#id-sel-' + i + '').val();
        }
        console.log(dict);

        var myData = JSON.stringify(dict);

        $.ajax({
            type: 'POST',
            url: '/Create/Add',
            contentType: "application/json",
            dataType: 'json',
            data: myData,
            success: function (result) {
                console.log('Data received: ');
                console.log(result);
            }
        });
        document.getElementById("h2").innerHTML = "Добавлено";
    });
</script>

WebJsonToDB/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    string s = ViewBag.Name;
    
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["name"]</h3>

<p>@ViewBag.Name</p>

WebJsonToDB/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebJsonToDB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    @TempData["temp"]
</div>

<br />
<br />
<div class="c1">
    <div class="dropdown c2">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
            Tables
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            @foreach (var i in ViewBag.Tables)
            {
                @foreach (var k in i)
                {
                    <li><a asp-controller="Open" asp-action="Index" asp-route-nameTable="@k.Value">@k.Value</a></li>
                }
            }
        </ul>
    </div>
<a asp-controller="Create" asp-action="Index"><button class="btn btn-info">CreateTable</button></a>
</div>

WebJsonToDB/Views/Open/Create.cshtml
@{
    ViewData["Title"] = "Create";
    int j = 0;
}

<h2>Create</h2>

<div class="form-horizontal">
    <hr />
        @foreach (var i in ViewBag.ColumsName)
        {
        <div class="form-group">
            <div class="col-md-10">
                <label class="control-label col-md-2">@i: </label>
                <input name="par" id="@j"/><br />
            </div>
        </div>
            j++;
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="sub" value="Save" class="btn btn-default" />
            </div>
        </div>
</div>
<h2 id="h2"></h2>
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
<script>
    $('#sub').click(function (e) {
        e.preventDefault();
        
        var dict = {};

        var stringArray = @Html.Raw(Json.Serialize(ViewBag.ColumsName));
        for (var i = 0; i < @j; i++) {
            dict[stringArray[i]] = $('#' + i + '').val();
        }
        console.log(dict);

        var myData = JSON.stringify(dict);

        $.ajax({
            type: 'POST',
            url: '/Open/Create',
            contentType: "application/json",
            dataType: 'json',
            data: myData,
            success: function (result) {
                console.log('Data received: ');
                console.log(result);
            }
        });
        document.getElementById("h2").innerHTML = "Добавлено";
        });
</script>
<a asp-controller="Open" asp-action="Redirect">Назад</a>

WebJsonToDB/Views/Open/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

WebJsonToDB/Views/Open/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    List<dynamic> values = ViewBag.Values;
}

<h2>Edit</h2>

<div class="form-horizontal">
    <hr />
    <form method="post" action="~/Open/Edit">
        @foreach (var i in ViewBag.RowInfo)
        {
            foreach (var k in i)
            {
            <div class="form-group">
                <div class="col-md-10">
                    <label class = "control-label col-md-2">@k.Key: </label>
                    <input name="par" value="@k.Value" /><br />
                </div>
            </div>
            }
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </form>
</div>

WebJsonToDB/Views/Open/Index.cshtml
@{
    ViewData["Title"] = "Open";
    string table = ViewBag.Table;
    int count = ViewBag.Count;
    List<dynamic> id = ViewBag.Id;
    int j = 0;
}

<h2>Open</h2>
<h3>@table</h3>

<a asp-controller="Open" asp-action="Create" asp-route-table="@table">Create New</a>
<table class="table table-bordered table-responsive table-hover">
    <tr>
        @foreach (var i in ViewBag.ColumNames)
        {
            <th>
                @i
            </th>
        }
    </tr>

    @foreach (var i in ViewBag.Colums)
    {

    <tr>
        @foreach (var k in i)
            {
        <td>
            @k.Value
        </td>
            }
        <td class="tdborder">
            <a asp-controller="Open" asp-action="Delete" asp-route-id="@id[j]" asp-route-table="@table" asp-route-fcolumn="@ViewBag.FColumn">Delete</a> |
            <a asp-controller="Open" asp-action="Edit" asp-route-id="@id[j]" asp-route-table="@table" asp-route-fcolumn="@ViewBag.FColumn">Edit</a>
        </td>
    </tr>
    j++;
    }

</table>

WebJsonToDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebJsonToDB</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebJsonToDB</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebJsonToDB</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>